# Generated by Django 5.0.6 on 2024-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_users_course_subscribers_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses_files/'),
        ),
    ]
